# Generated by Django 3.0 on 2020-09-08 05:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True, verbose_name='Nombre de la Categoría')),
            ],
            options={
                'verbose_name_plural': 'Categorias',
                'ordering': ['id'],
            },
        ),
    ]
